version: "3"
services:
  git:
    container_name: git
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PASSWORD: ${PASSWORD}
    ports:
      - "${PORT}:22"
    volumes:
      - '${REPOS}:/home/git/repos'
      - '${REPOS}:/repos'
    restart: unless-stopped

