version: "3"
services:
  git:
    container_name: git
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2222:22"
    volumes:
      - './repos:/home/git/repos'
      - './.ssh:/home/git/.ssh'
    restart: unless-stopped

